version: '3.9'

services:
  gateway:
    image: cleancadet/gateway:${GATEWAY_VERSION-latest}
    build:
      context: build/gateway
      target: ${GATEWAY_BUILD_TARGET:-gatewayWithFront}
      args:
        - SMART_TUTOR_API_URL=${SMART_TUTOR_FRONT_API_URL}
        - KEYCLOAK_ON=${KEYCLOAK_ON}
        - KEYCLOAK_AUTH_URL=${KEYCLOAK_FRONTEND_URL:-}
        - KEYCLOAK_REALM=${SMART_TUTOR_FRONT_KEYCLOAK_REALM:-}
        - KEYCLOAK_AUDIENCE=${AUDIENCE:-}
    restart: on-failure
    networks:
      - public
      - application
    ports:
      - "${GATEWAY_PUBLISHED_PORT-8080}:8080"
    depends_on:
      - smart-tutor
  smart-tutor:
    image: cleancadet/smart-tutor:${SMART_TUTOR_VERSION-latest}
    build:
      dockerfile: stacks/build/smart-tutor/Dockerfile
      context: ../
      target: ${SMART_TUTOR_BUILD_TARGET:-final}
    restart: on-failure
    networks:
      - application
      - database
    environment:
      STAGE: ${SMART_TUTOR_STAGE}
      DATABASE_HOST: ${SMART_TUTOR_DATABASE_HOST}
      DATABASE_PORT: ${SMART_TUTOR_DATABASE_PORT}
      DATABASE_PASSWORD: ${SMART_TUTOR_DATABASE_PASSWORD}
      DATABASE_USER: ${SMART_TUTOR_DATABASE_USERNAME}
      DATABASE_SCHEMA: ${SMART_TUTOR_DATABASE_SCHEMA}
      KEYCLOAK_ON: ${KEYCLOAK_ON}
      AUTHORITY: ${AUTHORITY:-}
      AUDIENCE: ${AUDIENCE:-}
      SMART_TUTOR_CORS_ORIGINS: ${SMART_TUTOR_CORS_ORIGINS}
    depends_on:
      - database
    volumes:
      - /data/corsorigins
  database:
    image: postgres:${POSTGRES_VERSION-13}
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ${SMART_TUTOR_DATA_INGEST_SCRIPT:-../SmartTutor/Database/Scripts/all.sql}
        target: /tmp/smart-tutor-init.sql
    ports:
      - ${POSTGRES_PUBLISHED_PORT-5432}:5432

volumes:
  database-data:
    name: clean-cadet-database

networks:
  public:
    name: public
    driver: bridge
  application:
    name: application
    driver: bridge
  database:
    name: database
    driver: bridge
