version: '3.9'

services:
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION-13.0.1}
    restart: on-failure
    networks:
      - database
      - application
    environment:
      PROXY_ADDRESS_FORWARDING: ${PROXY_ADDRESS_FORWARDING}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_FRONTEND_URL}
      DB_VENDOR: ${KEYCLOAK_DATABASE_VENDOR}
      DB_ADDR: ${KEYCLOAK_DATABASE_ADDR}
      DB_DATABASE: ${KEYCLOAK_DATABASE_SCHEMA}
      DB_USER: ${KEYCLOAK_DATABASE_USER}
      DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    depends_on:
      - database
  database:
    volumes:
      - type: bind
        source: ./config/database-init/keycloak.sql
        target: /docker-entrypoint-initdb.d/keycloak.sql
  gateway:
    depends_on:
      - keycloak
